//
// (w)ritten by Chuan-Liang Teng 2006, mailto:clteng@ms6.hinet.net
//

#include "gettypeinfo.h"

#include <stdio.h>

//
void GetMoreInformation(HDEVINFO hDevInfo, SP_DEVINFO_DATA spDevInfoData)
{
    GUID     guid       = {0};
    wchar_t  szName[128] = {0};
    DWORD    dwAddr;

    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_BUSNUMBER, 0L, (PBYTE)&dwAddr, sizeof(DWORD), 0))
    {
        printf ("  BUS Number: %X\n", dwAddr);
    }

    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_CAPABILITIES, 0L, (PBYTE)&dwAddr, sizeof(DWORD), 0))
    {
        if (dwAddr)
        {
            printf ("  Capabilities\n");
//
            if (dwAddr & CM_DEVCAP_LOCKSUPPORTED)
                printf("    LockSupported\n");
            if (dwAddr & CM_DEVCAP_EJECTSUPPORTED)
                printf("    EjectSupported\n");
            if (dwAddr & CM_DEVCAP_REMOVABLE)
                printf("    Removable\n");
            if (dwAddr & CM_DEVCAP_DOCKDEVICE)
                printf("    DockDevice\n");
            if (dwAddr & CM_DEVCAP_UNIQUEID)
                printf("    UniqueID\n");
            if (dwAddr & CM_DEVCAP_SILENTINSTALL)
                printf("    SilentInstall\n");
            if (dwAddr & CM_DEVCAP_RAWDEVICEOK)
                printf("    RawDeviceOK\n");
            if (dwAddr & CM_DEVCAP_SURPRISEREMOVALOK)
                printf("    SurpriseRemovalOK\n");
            if (dwAddr & CM_DEVCAP_HARDWAREDISABLED)
                printf("    HardwareDisabled\n");
            if (dwAddr & CM_DEVCAP_NONDYNAMIC)
                printf("    NonDynamic\n");
        }
    }

    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_CHARACTERISTICS, 0L, (PBYTE)&dwAddr, sizeof(DWORD), 0))
    {
        if (dwAddr)
        {
            printf("  Characteristics\n");
//
            if (dwAddr & FILE_DEVICE_SECURE_OPEN)
                printf("    DEVICE_SECURE_OPEN\n");
            if (dwAddr & FILE_FLOPPY_DISKETTE)
                printf("    FLOPPY_DISKETTE\n");
            if (dwAddr & FILE_READ_ONLY_DEVICE)
                printf("    READ_ONLY_DEVICE\n");
            if (dwAddr & FILE_REMOVABLE_MEDIA)
                printf("    REMOVABLE_MEDIA\n");
            if (dwAddr & FILE_WRITE_ONCE_MEDIA)
                printf("    WRITE_ONCE_MEDIA\n");
            if (dwAddr & FILE_REMOTE_DEVICE)
                printf("    REMOTE_DEVICE\n");
            if (dwAddr & FILE_DEVICE_IS_MOUNTED)
                printf("    DEVICE_IS_MOUNTED\n");
            if (dwAddr & FILE_VIRTUAL_VOLUME)
                printf("    VIRTUAL_VOLUME\n");
            if (dwAddr & FILE_AUTOGENERATED_DEVICE_NAME)
                printf("    AUTOGENERATED_DEVICE_NAME\n");
        }
    }

    // Each device object has a device type, which is stored in the DeviceType member
    // of its DEVICE_OBJECT structure. The device type represents the type of
    // underlying hardware for the driver.

    // Every kernel - mode driver that creates a device object must specify an
    // appropriate device type value when calling IoCreateDevice.The IoCreateDevice
    // routine uses the supplied device type to initialize the DeviceType member of
    // the DEVICE_OBJECT structure.
    // See https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/specifying-device-types
    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_DEVTYPE, 0L, (PBYTE)&dwAddr, sizeof(DWORD), 0))
    {
        if (dwAddr)
        {
            printf("  Device Type\n");
//
            if (dwAddr & FILE_DEVICE_8042_PORT)
                printf("    DEVICE_8042_PORT\n");
            if (dwAddr & FILE_DEVICE_ACPI)
                printf("    DEVICE_ACPI\n");
            if (dwAddr & FILE_DEVICE_BATTERY)
                printf("    DEVICE_BATTERY\n");
            if (dwAddr & FILE_DEVICE_BEEP)
                printf("    DEVICE_BEEP\n");
            if (dwAddr & FILE_DEVICE_BUS_EXTENDER)
                printf("    DEVICE_BUS_EXTENDER\n");
            if (dwAddr & FILE_DEVICE_CD_ROM)
                printf("    DEVICE_CD_ROM\n");
            if (dwAddr & FILE_DEVICE_CD_ROM_FILE_SYSTEM)
                printf("    DEVICE_CD_ROM_FILE_SYSTEM\n");
            if (dwAddr & FILE_DEVICE_CHANGER)
                printf("    DEVICE_CHANGER\n");
            if (dwAddr & FILE_DEVICE_CONTROLLER)
                printf("    DEVICE_CONTROLLER\n");
            if (dwAddr & FILE_DEVICE_DATALINK)
                printf("    DEVICE_DATALINK\n");
            if (dwAddr & FILE_DEVICE_DFS)
                printf("    DEVICE_DFS\n");
            if (dwAddr & FILE_DEVICE_DFS_FILE_SYSTEM)
                printf("    DEVICE_DFS_FILE_SYSTEM\n");
            if (dwAddr & FILE_DEVICE_DFS_VOLUME)
                printf("    DEVICE_DFS_VOLUME\n");
            if (dwAddr & FILE_DEVICE_DISK)
                printf("    DEVICE_DISK\n");
            if (dwAddr & FILE_DEVICE_DISK_FILE_SYSTEM)
                printf("    DEVICE_DISK_FILE_SYSTEM\n");
            if (dwAddr & FILE_DEVICE_DVD)
                printf("    DEVICE_DVD\n");
            if (dwAddr & FILE_DEVICE_FILE_SYSTEM)
                printf("    DEVICE_FILE_SYSTEM\n");
            if (dwAddr & FILE_DEVICE_FIPS)
                printf("    DEVICE_FIPS\n");
            if (dwAddr & FILE_DEVICE_FULLSCREEN_VIDEO)
                printf("    DEVICE_FULLSCREEN_VIDEO\n");
            if (dwAddr & FILE_DEVICE_INPORT_PORT)
                printf("    DEVICE_INPORT_PORT\n");
            if (dwAddr & FILE_DEVICE_KEYBOARD)
                printf("    DEVICE_KEYBOARD\n");
            if (dwAddr & FILE_DEVICE_KS)
                printf("    DEVICE_KS\n");
            if (dwAddr & FILE_DEVICE_KSEC)
                printf("    DEVICE_KSEC\n");
            if (dwAddr & FILE_DEVICE_MAILSLOT)
                printf("    DEVICE_MAILSLOT\n");
            if (dwAddr & FILE_DEVICE_MASS_STORAGE)
                printf("    DEVICE_MASS_STORAGE\n");
            if (dwAddr & FILE_DEVICE_MIDI_IN)
                printf("    DEVICE_MIDI_IN\n");
            if (dwAddr & FILE_DEVICE_MIDI_OUT)
                printf("    DEVICE_MIDI_OUT\n");
            if (dwAddr & FILE_DEVICE_MODEM)
                printf("    DEVICE_MODEM\n");
            if (dwAddr & FILE_DEVICE_MOUSE)
                printf("    DEVICE_MOUSE\n");
            if (dwAddr & FILE_DEVICE_MULTI_UNC_PROVIDER)
                printf("    DEVICE_MULTI_UNC_PROVIDER\n");
            if (dwAddr & FILE_DEVICE_NAMED_PIPE)
                printf("    DEVICE_NAMED_PIPE\n");
            if (dwAddr & FILE_DEVICE_NETWORK)
                printf("    DEVICE_NETWORK\n");
            if (dwAddr & FILE_DEVICE_NETWORK_BROWSER)
                printf("    DEVICE_NETWORK_BROWSER\n");
            if (dwAddr & FILE_DEVICE_NETWORK_FILE_SYSTEM)
                printf("    DEVICE_NETWORK_FILE_SYSTEM\n");
            if (dwAddr & FILE_DEVICE_NETWORK_REDIRECTOR)
                printf("    DEVICE_NETWORK_REDIRECTOR\n");
            if (dwAddr & FILE_DEVICE_NULL)
                printf("    DEVICE_NULL\n");
            if (dwAddr & FILE_DEVICE_PARALLEL_PORT)
                printf("    DEVICE_PARALLEL_PORT\n");
            if (dwAddr & FILE_DEVICE_PHYSICAL_NETCARD)
                printf("    DEVICE_PHYSICAL_NETCARD\n");
            if (dwAddr & FILE_DEVICE_PRINTER)
                printf("    DEVICE_PRINTER\n");
            if (dwAddr & FILE_DEVICE_SCANNER)
                printf("    DEVICE_SCANNER\n");
            if (dwAddr & FILE_DEVICE_SCREEN)
                printf("    DEVICE_SCREEN\n");
            if (dwAddr & FILE_DEVICE_SERENUM)
                printf("    DEVICE_SERENUM\n");
            if (dwAddr & FILE_DEVICE_SERIAL_MOUSE_PORT)
                printf("    DEVICE_SERIAL_MOUSE_PORT\n");
            if (dwAddr & FILE_DEVICE_SERIAL_PORT)
                printf("    DEVICE_SERIAL_PORT\n");
            if (dwAddr & FILE_DEVICE_SMARTCARD)
                printf("    DEVICE_SMARTCARD\n");
            if (dwAddr & FILE_DEVICE_SMB)
                printf("    DEVICE_SMB\n");
            if (dwAddr & FILE_DEVICE_SOUND)
                printf("    DEVICE_SOUND\n");
            if (dwAddr & FILE_DEVICE_STREAMS)
                printf("    DEVICE_STREAMS\n");
            if (dwAddr & FILE_DEVICE_TAPE)
                printf("    DEVICE_TAPE\n");
            if (dwAddr & FILE_DEVICE_TAPE_FILE_SYSTEM)
                printf("    DEVICE_TAPE_FILE_SYSTEM\n");
            if (dwAddr & FILE_DEVICE_TERMSRV)
                printf("    DEVICE_TERMSRV\n");
            if (dwAddr & FILE_DEVICE_TRANSPORT)
                printf("    DEVICE_TRANSPORT\n");
            if (dwAddr & FILE_DEVICE_UNKNOWN)
                printf("    DEVICE_UNKNOWN\n");
            if (dwAddr & FILE_DEVICE_VDM)
                printf("    DEVICE_VDM\n");
            if (dwAddr & FILE_DEVICE_VIDEO)
                printf("    DEVICE_VIDEO\n");
            if (dwAddr & FILE_DEVICE_VIRTUAL_DISK)
                printf("    DEVICE_VIRTUAL_DISK\n");
            if (dwAddr & FILE_DEVICE_WAVE_IN)
                printf("    DEVICE_WAVE_IN\n");
            if (dwAddr & FILE_DEVICE_WAVE_OUT)
                printf("    DEVICE_WAVE_OUT\n");
        }
    }


    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_FRIENDLYNAME, 0L, (PBYTE)szName, sizeof(szName), 0))
    {
        printf("  Friendly name: %S\n", szName);
    }

    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_DEVICEDESC, 0L, (PBYTE)szName, sizeof(szName), 0))
    {
        printf("  Device Description: %S\n", szName);
    }

    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_MFG, 0L, (PBYTE)szName, sizeof(szName), 0))
    {
        printf("  Manufacturer: %S\n", szName);
    }

    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_DRIVER, 0L, (PBYTE)szName, sizeof(szName), 0))
    {
        printf("  Driver: %S\n", szName);
    }


    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_ENUMERATOR_NAME, 0L, (PBYTE)szName, sizeof(szName), 0))
    {
        printf("  Enumerator: %S\n", szName);
    };
//
    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_HARDWAREID, 0L, (PBYTE)szName, sizeof(szName), 0))
    {
        wchar_t *p = szName;
//
        printf ("  Hardware ID\n");
//
        while (*p)
        {
            printf ("    %S\n", p);
            p = wcschr(p, 0);
            *p++;
        }
    }
//
    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_LOCATION_INFORMATION, 0L, (PBYTE)szName, sizeof(szName), 0))
    {
        printf("  Local Information: %S\n", szName);
    }
//
    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_LOWERFILTERS, 0L, (PBYTE)szName, sizeof(szName), 0))
    {
        printf ("  Lower Filter: %S\n", szName);
    }
//
    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_UPPERFILTERS, 0L, (PBYTE)szName, sizeof(szName), 0))
    {
        printf ("  Upper Filter: %S\n", szName);
    }
//
    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_PHYSICAL_DEVICE_OBJECT_NAME, 0L, (PBYTE)szName, sizeof(szName), 0))
    {
        printf ("  Physical Device Object Name: %S\n", szName);
    };
//
    if (SetupDiGetDeviceRegistryProperty(hDevInfo, &spDevInfoData, SPDRP_SERVICE, 0L, (PBYTE)szName, sizeof(szName), 0))
    {
        wchar_t *p = szName;
//
        printf ("  Service Name\n");
        if (*p)
            GetDriverName(szName);

        printf("       driver name list\n");
        while (*p)
        {
            printf("         %S\n", p);
            p = wcschr(p, 0);
            p++;
#if 0
            while (wcschr(p, L'\\'))
            {
                printf ("         %S\n", p);
                p = wcschr(p, 0);
                p++;
            }
#endif
        }
            
    };

    printf("----------\n");
}

//
void GetDriverName(const wchar_t *szServiceName)
{
    HKEY  hKey             = 0L;
    wchar_t  szSubKey[128]    = {L"SYSTEM\\CurrentControlSet\\Services\\\0"};
    wchar_t  szPath[MAX_PATH] = {0};
    DWORD cbData;
    DWORD dwType;
    DWORD dwStart;
//
    wcscat_s(szSubKey, 128, szServiceName);
    if (RegOpenKeyEx(HKEY_LOCAL_MACHINE, szSubKey, 0, KEY_READ, &hKey) != ERROR_SUCCESS)
    {
        printf("     ImagePath: N/A\n");
        printf("     Group: N/A\n");
        printf("     Start: N/A\n");
        return;
    }
//
    cbData = MAX_PATH-1;
    dwType = REG_EXPAND_SZ;
    printf("     ImagePath: ");
    if (RegQueryValueEx(hKey, L"ImagePath", 0L, &dwType, (LPBYTE)szPath, &cbData) != ERROR_SUCCESS)
        printf("N/A\n");
    else
    {    
        wchar_t szRoot[MAX_PATH] = {0};
//
        GetWindowsDirectory(szRoot, MAX_PATH-1);
        wcscat_s(szRoot, MAX_PATH, L"\\");
        wcscat_s(szRoot, MAX_PATH, szPath);
        printf("%S\n", szRoot);
    }
//
    RtlZeroMemory(szPath, MAX_PATH);
    cbData = MAX_PATH-1;
    dwType = REG_SZ;
    printf("     Group: ");
    if (RegQueryValueEx(hKey, L"Group", 0L, &dwType, (LPBYTE)szPath, &cbData) != ERROR_SUCCESS)
        printf("N/A\n");
    else
        printf("%S\n", szPath);
//
    dwStart = 0;
    cbData  = sizeof(DWORD);
    dwType  = REG_DWORD;
    printf("     Start: ");
    if (RegQueryValueEx(hKey, L"Start", 0L, &dwType, (LPBYTE)&dwStart, &cbData) != ERROR_SUCCESS)
        printf("N/A\n");
    else
    {
        char szPath[64] = { 0 };

        switch(dwStart)
        {
            case SERVICE_BOOT_START:
                strcpy_s(szPath, 64, "BOOT START");
            break;
//
            case SERVICE_SYSTEM_START:
                strcpy_s(szPath, 64, "SYSTEM START");
            break;
//
            case SERVICE_AUTO_START:
                strcpy_s(szPath, 64, "AUTO START");
            break;
//
            case SERVICE_DEMAND_START:
                strcpy_s(szPath, 64, "DEMAND START");
            break;
//
            case SERVICE_DISABLED:
                strcpy_s(szPath, 64, "DISABLED");
            break;

            default:
                strcpy_s(szPath, 64, "Unknown");
                break;
//
        }
        printf ("%s\n", szPath);
    }
    RegCloseKey(hKey);
}